### ISSUE TITLE
 Get feedback from a designer about Website

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#178]
**Description:**

- What is the purpose/reason for this task?
To understand where we stand with our current design and what we can do better
- What current or future goal of the TF does it help achieve?
Having a good design could attract more attention and will make a better reputation

**Definition of done:**

- [x] Feedback is obtained and written down

**Comment by Mrak1985** [comment]
@Riae we can ask @MilicaSequeira what she thinks about the website

**Comment by MilicaSequeira** [comment]
I think that icons for non-profit, open source, white label, tonomy dao, tonomy id, infrastructure, legality and security are wrong for what they are representing. 
Also the illustration on the top and mid page are not consistent in style. 
Join us could pop up (if possible) instead of fully open discord because then the user isn’t anymore on the website and he came for that (most likely) or ask are you sure you want to go there? 
The colours are good if I’m asked. Wouldn’t change the colour of icons because the background animations match the colour of icons. Only the middle illustration is very off with the colours and generally I don’t like it. Its too big and takes away instead of add to the website.
The footer needs a bit og work or at least centering.
